### ISSUE TITLE
gob: unknown type id or corrupted data

### ISSUE THREAD

**Issue by DedAzaMarks** [alecthomas/go_serialization_benchmarks#103]
This is more question about go, rather than about benchmark. In gob serializer init function, after removing thees line
https://github.com/alecthomas/go_serialization_benchmarks/blob/6f010e2a1cfe9cfa584fa261929e49f7fd7fd26b/serialization_benchmarks_test.go#L406
https://github.com/alecthomas/go_serialization_benchmarks/blob/6f010e2a1cfe9cfa584fa261929e49f7fd7fd26b/serialization_benchmarks_test.go#L411
Unmarshal function returns `unmarshal error gob: unknown type id or corrupted data`. Could you please explain this?

Thank you

**Comment by pascaldekloe** [comment]
The `gob.Register` was missing.
Fixed in #107, explained in #36.

**Comment by alecthomas** [comment]
Thanks!
