### ISSUE TITLE
Skip running benchmarks for X if X fails to build

### ISSUE THREAD

**Issue by thomas708** [alecthomas/go_serialization_benchmarks#110]
Running command "go test -bench='.*' ./" results in this error:

```
#github.com/niubaoshu/gotiny
../../golang/pkg/mod/github.com/niubaoshu/gotiny@v0.0.3/unsafe.go:47:3: //go:linkname must refer to declared function or variable
FAIL	github.com/alecthomas/go_serialization_benchmarks [build failed]
FAIL
```

Seems like the issue is specifically with niubaoshu/gotiny package.  I'm not interested in this package yet it's a shame because of this I cannot run any other benchmarks and forced to take time to fix this first.

So hoping if it's possible to update such that if package X fails to build then skips it but build and run everything else?

**Comment by alecthomas** [comment]
That's not really possible, you'll have to comment those benchmarks out.

**Comment by alecthomas** [comment]
But I think given that the package no longer compiles and hasn't been fixed since Go 1.18, we should remove it altogether.

**Comment by alecthomas** [comment]
But for now I added a replace directive for a working fork.

**Comment by thomas708** [comment]
Thanks for the response and quick fix!
