### ISSUE TITLE
Gogoprotobuf Alternative?

### ISSUE THREAD

**Issue by FrankDMartinez** [alecthomas/go_serialization_benchmarks#116]
Hi.

I hope you are having a great new year so far. With gogoprotobuf being deprecated by the author, which option would you recommend in its place?

Thanks in advance.

**Comment by alecthomas** [comment]
Probably standard protobuf, and for performance probably https://github.com/planetscale/vtprotobuf

**Comment by FrankDMartinez** [comment]
Thanks, do you have any correctness concerns with vtprotobuf?

**Comment by alecthomas** [comment]
No definitely not, it is used under heavy production loads by Vitess. Any correctness issues would have been shaken out already.

**Comment by FrankDMartinez** [comment]
Thanks!
