### ISSUE TITLE
Buffer Reuse Inconsistency Again

### ISSUE THREAD

**Issue by ymz-ncnk** [alecthomas/go_serialization_benchmarks#129]
BENC reuses the buffer in its Pre benchmarks, but as I understand, it was decided not to allow this behavior (#107) @deneonet.

**Comment by deneonet** [comment]
Because it is reusing the buffer, it is created in a new benchmark, if it bothers you I can add a notice there.

**Comment by ymz-ncnk** [comment]
No, it doesn't bothers me. I'm just reminding that earlier a decision was made to remove all such code from separate benchmarks. And now we will start adding them again... Do you understand what I mean?

**Comment by ymz-ncnk** [comment]
There was an open issue #106 and after it #107.

**Comment by deneonet** [comment]
Okay, my bad. I remove the benchmark.

**Comment by deneonet** [comment]
Heres the pull request: #131

**Comment by alecthomas** [comment]
I'm actually not against pre-allocating buffers, but if we were to allow it it would have to be very clear which benchmarks were pre-allocated and which weren't.

Basically, I don't have an issue with any particular optimisations as long as it's very clear what they are and what the tradeoffs are.
