### ISSUE TITLE
supporting MarshalTap

### ISSUE THREAD

**Issue by nazarifard** [alecthomas/go_serialization_benchmarks#149]

**Comment by kenshaw** [comment]
@nazarifard it's really not kind to `@` all of these people, especially since we are not maintainers of this project, nor are we involved in any way. Please don't abuse the `@`. Thank you.

**Comment by nazarifard** [comment]
> @nazarifard it's really not kind to `@` all of these people, especially since we are not maintainers of this project, nor are we involved in any way. Please don't abuse the `@`. Thank you.

i removed that. unfortunately it has not delete option. please close that.
