### ISSUE TITLE
Adding CBOR serializers

### ISSUE THREAD

**Issue by client9** [alecthomas/go_serialization_benchmarks#16]
CBOR is msgpack-like format on IETF standards track (RFC 7049)

* http://cbor.io
* https://tools.ietf.org/html/rfc7049

Golang implementations are:

* https://code.google.com/p/cbor/
* https://github.com/2tvenom/cbor

Both seem to have high level API interfaces that serialise arbitrary structs, so I think they can be added without too much work.  I will try to add them in a pull request, unless you beat me to it.

If anyone has found them to be unstable or broken, please let me know.

thanks all!

nickg

**Comment by brianolson** [comment]
I think that google code cbor link was mine, and it has moved to butbucket
https://bitbucket.org/bodhisnarkva/cbor
aka
import cbor "bitbucket.org/bodhisnarkva/cbor/go"

**Comment by alecthomas** [comment]
Unfortunately I don't have time to add benchmarks for all serialisers, but I'd welcome PRs.

**Comment by dumblob** [comment]
It seems the repo https://bitbucket.org/bodhisnarkva/cbor/go got migrated to GitHub to https://github.com/brianolson/cbor_go .
