### ISSUE TITLE
Generate* functions seem to not be equivalent 

### ISSUE THREAD

**Issue by rw** [alecthomas/go_serialization_benchmarks#30]
I noticed that the `generate*` call varies with the benchmark. This may lead to bad comparisons between formats.

In particular, FlatBuffers uses the original `generate` call, whereas GogoProtoBuf uses `generateGogoProto`.

Am I right in understanding this?

**Comment by alecthomas** [comment]
You are correct, but this is intentional. The idea is to benchmark raw serialisation speed as much as possible. To that end, the generation [isn't part of the benchmark](https://github.com/alecthomas/go_serialization_benchmarks/blob/master/serialization_benchmarks_test.go#L259) at all.

**Comment by rw** [comment]
@alecthomas That makes sense now that you explain it, and I also think it's unusual. I think that most people don't adopt the `type`s of the serialization format as their native type. These serialization formats aren't used like that most of the time. 

With something like FlatBuffers, you can use your app-specific type definitions, then convert it (potentially with no overhead, if you have a `Builder` already waiting) to a `[]byte` slice. With Protobufs, you first have to turn your app-specific type into the PB version of that object, then serialize that to a `[]byte` slice.

So, I guess I'm curious: would it be useful to have a second GogoProtobuf benchmark that converts from the original objects?

**Comment by alecthomas** [comment]
Yes, I can see how that would be useful definitely.
