### ISSUE TITLE
Fair Comparison For Timestamps

### ISSUE THREAD

**Issue by pascaldekloe** [alecthomas/go_serialization_benchmarks#32]
The test data struct has a time.Time field. Formats which don't support timestamps now benefit from the fact that they compete with a plain integer.
To be fair, we could create time.Unix objects and make BirthDay as time.Now().Round(time.Seconds) to get rid of the nanoseconds or simply switch to int64 for all.

**Comment by alecthomas** [comment]
The benchmarks are meant to represent how the serialisers will be used in reality. Yes, some support `time.Time` and some don't. But if they do support `time.Time` that is how people will use them, and that is what is benchmarked.

At the end of the day, generic benchmarks such as this are only going to get you so far. There really is no substitution for benchmarking real data and that is beyond the scope of this project.

**Comment by pascaldekloe** [comment]
Either you use time.Time in your code or you don't.
* If you do then every parse requires a malloc, even when the wire format is int64. Don't hide this.
* If you don't and use a time.Time for the wire format anyway then that's just stupid. Don't base a benchmark on such mistake.

**Comment by alecthomas** [comment]
I can see that this conversation is spiralling, so that's enough for me.
