### ISSUE TITLE
Fair Comparison For FlatBuffer Lazy Parsing

### ISSUE THREAD

**Issue by pascaldekloe** [alecthomas/go_serialization_benchmarks#35]
BenchmarkFlatBuffersUnmarshal measures the performance of goserbench.FlatBufferA.Init which does only the initiation. Most of the work is done in the "getters".
To be fair, we could read the fields into a goserbench.A instance.

**Comment by rw** [comment]
I agree it's important to benchmark it correctly. How often do these results get re-generated?

**Comment by pascaldekloe** [comment]
Hi Robert, What do you mean by "these results" and "re-generated"?

**Comment by alecthomas** [comment]
I think it would be useful to benchmark reading fields, but it would also have to be implemented consistently for the other serialisers.

**Comment by pascaldekloe** [comment]
Will do.

**Comment by FiloSottile** [comment]
Done in 20e25c1a4f06c2d249f18a3046e58f9cf6c0e1aa
