### ISSUE TITLE
gob fairness

### ISSUE THREAD

**Issue by robzan8** [alecthomas/go_serialization_benchmarks#36]
Hi.
Why not using the same instance of gob Encoder/Decoder, instead of creating a new one for each marshall/unmarshall operation? Seems to me that it would be more fair... what protobuf does once at generate time, gob can do at runtime, but just once! Otherwise consider removing gob from the benchmark, it makes it seem really bad while it probably isn't.

**Comment by name5566** [comment]
I agree with you. It make a misunderstanding on Gob. Gob is the same fast as protobuf in my tests.

**Comment by alecthomas** [comment]
I'd welcome a PR for this. I [tried](https://github.com/alecthomas/go_serialization_benchmarks/tree/faster_gob/36), but kept getting corrupt message errors:

```
BenchmarkGobMarshal-8  	 1000000	      1207 ns/op	      48 B/op	       2 allocs/op
BenchmarkGobUnmarshal-8	b=61
--- FAIL: BenchmarkGobUnmarshal-8
	serialization_benchmarks_test.go:114: gob failed to unmarshal: gob: unknown type id or corrupted data (<��b9b2b4faa77947cf�4���IL�
		1ca61f574b��Y�K���?)
ok  	github.com/alecthomas/go_serialization_benchmarks	1.244s
```

**Comment by robzan8** [comment]
I'm pretty sure I understand where the issue comes from.
The first time a gob encoder encodes a value of a certain type that has never encountered before, it also transmits type information needed by the decoder for that type.
in function benchUnmarshal, ser[0] also contains serialized type info that is needed to decode elements of type A. So, for everything to work correctly, ser[0] should be the first thing decoded by the decoder.
Unfortunately, the decoder chooses at random what to decode, and it reports that a value with unknown type id has been encountered.
To fix the problem, ser[0] should be decoded only once, before anything else (before some other ser[i]). Another thing that may work is calling gob.Register(a) (where "a" is a value of type A), before doing the encoding/decoding (former method works for sure, I'm not sure about the latter).
I may be able to do a PR in the next few days.

**Comment by robzan8** [comment]
I can't run the benchmarks on master because zombiezen.com/go/capnproto2 has been moved.
I tried go-getting https://github.com/zombiezen/go-capnproto2
but I get the following error:
can't load package: package github.com/zombiezen/go-capnproto2: code in directory $GOPATH/src/github.com/zombiezen/go-capnproto2 expects import "zombiezen.com/go/capnproto2"

Am I missing something?

**Comment by alecthomas** [comment]
zombiezen.com/go/capnproto2 uses a go-import meta redirect, so it should still work. It works for me:

```
[alec@cavern:~/Projects/go_serialization_benchmarks]go get -u zombiezen.com/go/capnproto2
[alec@cavern:~/Projects/go_serialization_benchmarks]
```

**Comment by robzan8** [comment]
zombiezen.com/go/capnproto2 was down yesterday when I tried; works now.

**Comment by pascaldekloe** [comment]
Before first use you to `gob.Register`. That's where the errors came from.
