### ISSUE TITLE
correction to claim that go-capnproto truncates times

### ISSUE THREAD

**Issue by glycerine** [alecthomas/go_serialization_benchmarks#41]
With regards to go-capnproto, it is inaccurate and misleading to claim that the serialization format is what is truncating off the nanoseconds. Rather, when you set the time in your application code, you yourself are doing the truncation. Referencing:

https://github.com/alecthomas/go_serialization_benchmarks/commit/c2d096af9b0db064fc16dbf82d82cb74f8534de0#diff-f17176f7f172638627ca7eb38f7d873cR485

If you wish to store nanoseconds, then use UnixNano() instead of Unix().

**Comment by alecthomas** [comment]
I didn't write that code (as you can see from the commit header), but thanks for pointing it out.
