### ISSUE TITLE
capnproto misuse

### ISSUE THREAD

**Issue by glycerine** [alecthomas/go_serialization_benchmarks#42]
With regards to capnproto, capnproto bytes actually requires much less time (no additional beyond the I/O time for C++ code, and minimal for Go) to decode. 

Your application code example is introducing extra unnecessary copying. To avoid this, use the Bytes() methods commented below to point to the strings in memory rather than copy them unnecessarily.

from https://github.com/alecthomas/go_serialization_benchmarks/blob/master/serialization_benchmarks_test.go#L496

~~~
func (x *CapNProtoSerializer) Unmarshal(d []byte, i interface{}) error {
	a := i.(*A)
	s, _, _ := capn.ReadFromMemoryZeroCopy(d)
	o := ReadRootCapnpA(s)
	a.Name = string(o.Name())  // declare Name to be []byte, and use NameBytes() to minimize copying/allocation
	a.BirthDay = time.Unix(o.BirthDay(), 0)
	a.Phone = string(o.Phone())  // as above, use PhoneBytes()
	a.Siblings = int(o.Siblings())
	a.Spouse = o.Spouse()
	a.Money = o.Money()
	return nil
}
~~~

**Comment by alecthomas** [comment]
Thanks for letting me know, though in future a pull request probably would have been much more expedient for all concerned. You can create a pull request directly from GitHub by editing the file.
