### ISSUE TITLE
thrift benchmarks available.

### ISSUE THREAD

**Issue by glycerine** [alecthomas/go_serialization_benchmarks#45]
I added Thrift Binary and CompactBinary benchmarks to my fork. Feel free to pull from

https://github.com/glycerine/go_serialization_benchmarks

if you wish.

**Comment by alecthomas** [comment]
I'd be happy to pull. Once #44 is merged I will do so, thanks.

**Comment by alecthomas** [comment]
Please reopen if #44 is split into two benchmarks.
