### ISSUE TITLE
Stable input for benchmarks

### ISSUE THREAD

**Issue by LK4D4** [alecthomas/go_serialization_benchmarks#50]
I wonder what the idea behind choosing random elements on each benchmark step. I thought it would be nice to generate an item at the beginning of benchmarks and then use it for all operations. We could measure throughput with SetBytes in that case, and also, I think it would be a slightly more honest benchmark.
Thanks!

**Comment by LK4D4** [comment]
ping @alecthomas

**Comment by alecthomas** [comment]
I'm doubtful it would make much difference, but if you'd like to create a PR, go for it.
