### ISSUE TITLE
FlatBuffers can unmarshal without any allocations, yet there are some in the benchmark

### ISSUE THREAD

**Issue by rw** [alecthomas/go_serialization_benchmarks#51]
Hi,

I noticed that the following code seems to be creating heap allocations, which may reflect unfairly on flatbuffers: https://github.com/alecthomas/go_serialization_benchmarks/blob/master/serialization_benchmarks_test.go#L475-L477

The code in question is:
```go
	a.Name = string(o.Name())
	a.BirthDay = time.Unix(o.BirthDay(), 0)
	a.Phone = string(o.Phone())
```

Both `string` calls will create an allocation. FlatBuffers returns a `[]byte` which should be sufficient :-)

**Comment by alecthomas** [comment]
The struct has string fields, so they have to get transformed somehow...? I understand that you could change the fields to `[]byte` but if you actually need strings, then you'd have to do this anyway no?

**Comment by rw** [comment]
@alecthomas I updated FlatBuffers to use no heap allocations for reading a `string`. Will you please pull from master and re-run the benchmarks? :-)

**Comment by alecthomas** [comment]
Sure, create a PR and I'll take a look.

**Comment by rw** [comment]
It's opaque, no changes on your end besides using the latest version of the
library.

**Comment by rw** [comment]
Ah, nevermind. I see you are manually casting the byte slices using `string`. I'll look into using the new zero-alloc `string` function for the generated code.

**Comment by alecthomas** [comment]
👍
