### ISSUE TITLE
Add Result Size Information

### ISSUE THREAD

**Issue by kokizzu** [alecthomas/go_serialization_benchmarks#56]
It would be interesting to show the produced binary/encoding size.

**Comment by alecthomas** [comment]
That would be interesting, but I don't know how to achieve that within Go's benchmark framework. I guess you'd just need to manually print the mean at the end.

**Comment by jonomacd** [comment]
First of all, thanks for this! It is really useful and currently a main source for helping me decide on a format for a project I am working on.  One of my main requirements is output size. It would be great to see that information even if it is in another table. I might look at doing a PR

**Comment by ERnsTL** [comment]
That would be interesting indeed.

**Comment by markschmid** [comment]
Interested in this as well.

**Comment by pascaldekloe** [comment]
Went for the average instead @alecthomas. The floating-point metrics seem like a nice fit.
