### ISSUE TITLE
Build broken: goavro v2 support

### ISSUE THREAD

**Issue by taiyangc** [alecthomas/go_serialization_benchmarks#64]
Currently unable to benchmark locally:

```
$ go get -u -t
# github.com/alecthomas/go_serialization_benchmarks
./structdef_avro.go:11:10: undefined: goavro.Record
```

Need to support v1 and v2 versions. Quick fix is changing current import from `"github.com/linkedin/goavro"` to `goavro "gopkg.in/linkedin/goavro.v1"`

**Comment by alecthomas** [comment]
Can you send a PR?
