### ISSUE TITLE
JSON benchmarks corrupted

### ISSUE THREAD

**Issue by uberhalit** [alecthomas/go_serialization_benchmarks#68]
I found it very strange that the encoding and decoding benchmark results for `encoding/json` are almost the same while in pretty much any other benchmark you'll find online the decoding speed is way slower.

Additionally the speed of `JsonIter` seemed rather slow compared to `EasyJson` while in reality they should be pretty close.

![00](https://user-images.githubusercontent.com/19159295/43910695-d36149a8-9bfd-11e8-904b-02176d5a23da.png)

After digging around a bit I found that `structdef_easyjson.go > MarshalJSON()` and `structdef_easyjson.go > UnmarshalJSON()` were the culprit. These apparently override functions in both of the other libraries and thus alter their results.
Renaming them fixes the JSON benchmarks:

![01](https://user-images.githubusercontent.com/19159295/43910812-20f70fb8-9bfe-11e8-9875-75618af9dd02.png)

`structdef_easyjson.go:`
```golang
func (v *A) MarshalJSON2() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson_encode_go_serialization_benchmarks_A(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}
func (v *A) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson_encode_go_serialization_benchmarks_A(w, v)
}
func (v *A) UnmarshalJSON2(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson_decode_go_serialization_benchmarks_A(&r, v)
	return r.Error()
}
```
`serialization_benchmarks_test.go:`
```golang
func (m EasyJSONSerializer) Marshal(o interface{}) []byte {
	out, _ := o.(*A).MarshalJSON2()
	return out
}
func (m EasyJSONSerializer) Unmarshal(d []byte, o interface{}) error {
	err := o.(*A).UnmarshalJSON2(d)
	return err
}
```

JsonIter can further be sped up by using `jsoniter.ConfigFastest`:

![03](https://user-images.githubusercontent.com/19159295/43910928-65584640-9bfe-11e8-8447-b242f00e76f4.png)

**Comment by alecthomas** [comment]
Mind sending a PR...

**Comment by uberhalit** [comment]
done

**Comment by alecthomas** [comment]
Thank you very much!
