### ISSUE TITLE
gob benchmark results are unrealistic and unfair

### ISSUE THREAD

**Issue by vmihailenco** [alecthomas/go_serialization_benchmarks#86]
Last time I checked gob is the slowest encoding you can have in Go - yet in your benchmark it is the fastest. The reason seems to be that it is the only serializer that reuses encoder, decoder, and buffer. That is completely unrealistic and unfair. I understand that gob is slow without those optimizations but I doubt it is the right way to deal with it.

**Comment by vmihailenco** [comment]
PS To be fair - gob is not the only serializer that has this optimization. It is still unfair that some serializers have it and some don't.

**Comment by alecthomas** [comment]
It is not the fastest at all. msgp, gotiny, flatbuffers, capnproto, etc. are all faster or similar.

But no I don't think it's unreasonable or unfair. That's the documented way to use the gob package.

If some serialisers don't have this optimisation, that's just an omission, not deliberate.

**Comment by vmihailenco** [comment]
>It is not the fastest at all. msgp, gotiny, flatbuffers, capnproto, etc. are all faster or similar

That is another problem with this benchmark - you compare "full-featured" serializers like gob and code generation approach. Code generation will be faster every time than any reflect-based serializer.

**Comment by alecthomas** [comment]
If course they're compared, they achieve the same goal. It would be good to have a table in the README indicating this though, agreed.
