### ISSUE TITLE
Some "clever" optimizations used by some libs

### ISSUE THREAD

**Issue by vmihailenco** [alecthomas/go_serialization_benchmarks#87]
One particular example is reusing/sharing data for incoming `[]byte`

```go
package main

import (
	"fmt"

	"github.com/shamaton/msgpack"
)

func main() {
	type Struct struct {
		String string
	}
	v := Struct{String: "msgpack"}

	d, err := msgpack.Encode(v)
	if err != nil {
		panic(err)
	}

	r := Struct{}
	err = msgpack.Decode(d, &r)
	if err != nil {
		panic(err)
	}

	fmt.Println("before", r.String)

	// Overwrite []byte
	for i := range d {
		d[i] = 1
	}

	fmt.Println("after", r.String)
}
```

The result is

```
before msgpack
after 
```

I personally think it is an unacceptable practice and is not usable in the real world. WDYT?

**Comment by alecthomas** [comment]
Can you link me to the code in this repo that you're referring to?

**Comment by vmihailenco** [comment]
Well, you definitely have this serializer included in the repo and it uses "no copy" optimization always and by default. That said - this is not worth the time - it is already impossible to distill any truth without deep dive. At least I can't and I have more than basic knowledge about serialization... Thank you for the benchmark anyway :)
