### ISSUE TITLE
Feature request: add benchmark for google protobuf

### ISSUE THREAD

**Issue by hzxuzhonghu** [alecthomas/go_serialization_benchmarks#99]
As golang protobuf readme said: 

```
It has been superseded by the google.golang.org/protobuf module, which contains an updated and simplified API, support for protobuf reflection, and many other improvements. We recommend that new code use the google.golang.org/protobuf module.
```

Could you provide the comparison with https://github.com/protocolbuffers/protobuf-go?

**Comment by fahimbagar** [comment]
Hi @alecthomas. I've added protobuf: https://github.com/alecthomas/go_serialization_benchmarks/pull/174 
Anyway, thanks for the awesome project. This really helped me make my point. :smile:

**Comment by hzxuzhonghu** [comment]
Great thanks
